# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: /:title
title: jordifierro's
email:
description: > # this means to ignore newlines until "baseurl:"
  Full stack developer (mainly Android + Rails), algorithm lover (c++),
  lean projects creator and never-ending learner.
  I'll try to write some useful stuff here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jordifierro.github.io" # the base hostname & protocol for your site
twitter_username: jordifierro
github_username:  jordifierro

# Build settings
markdown: kramdown
